### ISSUE TITLE
Service Locator of controllers is replaced with `service_container` by ClassParser

### ISSUE THREAD

**Issue by Chikashi-Kato** [RickySu/RSDiExtraBundle#4]
After upgrading to version 2 along with Symfony 5, the service locator of the controllers stopped working and my controllers now can't access the services defined in AbstractController such as `parameter_bag`.

After some investigation, I realized that version 2 of RSDiExtraBundle injects `service_container` to controllers by calling `setContainer` in [ClassParser](https://github.com/RickySu/RSDiExtraBundle/blob/master/Converter/Parser/ClassParser.php#L61). 

![image](https://github.com/RickySu/RSDiExtraBundle/assets/2705365/d39a39a9-20c5-47da-89b2-811ba93d1669)

This overwrites the service locator injected by Symfony framework and causes the issue I descrived above.

According to the commit log, this is necessary for Symfony 5.3 support, but could you teach me about it a bit more?
Also, is there any way to make `parameter_bag` and other services defined in getSubscribedServices accessible?

I appreciate your kind support!

P.S. my controllers are using `autowiring` and `autoconfiguration` enabled through DiExtraBundle's service annotation.

**Comment by RickySu** [comment]
RSDiExtraBundle doesn't support ServiceLoader currently.
You can use [**@Inject**](https://github.com/RickySu/RSDiExtraBundle/blob/master/Resources/doc/annotations.md#inject)  annotation for parameters inject in controller rather than "$this->container->get('xxx')"
 Or you can use a simple trait to resolve this issue.
 
 ```php

use RS\DiExtraBundle\Annotation as DI;
use Symfony\Component\DependencyInjection\ParameterBag\ParameterBagInterface;

trait ParameterTrait
{
    /**
     * @DI\Inject("parameter_bag")
     * @var ParameterBagInterface
     */
    protected $parameterBag;

    protected function getParameter(string $name)
    {
        return $this->parameterBag->get($name);
    }
}
```

**Comment by Chikashi-Kato** [comment]
Hi Ricky, thank you so much for your prompt reply!
I think your workaround works in my case. I appreciate your idea.

Thank you for maintaining this library!
